/* ==========================================================
   Catálogo XPRESS Fitness PRO
   Para agregar, quitar o cambiar precios, edita solo este archivo.
   - precio / precioAntes: en soles (precioAntes es opcional; solo si es real).
   - precioPar: opcional, para mancuernas.
   - imagenes: la primera es la principal; las demás se ven en el visor.
   ========================================================== */

const CATEGORIAS = {
  cardio: { nombre: "Cardio", titulo: "Cardio: sube el ritmo", bajada: "Bicicletas de spinning, elíptica y trotadoras para sumar minutos de movimiento a tu semana." },
  fuerza: { nombre: "Fuerza", titulo: "Fuerza: construye desde la base", bajada: "Mancuernas, bancas y barras para trabajar todo el cuerpo, a tu propio ritmo de avance." },
  core: { nombre: "Core", titulo: "Core: trabaja el centro", bajada: "Bancas abdominales, AB Shaper y AB Coaster para sumar abdomen a tu rutina semanal." },
  "linea-rosa": { nombre: "Línea rosa", titulo: "Línea rosa: para empezar con confianza", bajada: "Pesas compactas y livianas, pensadas para quienes recién arman su rutina de fuerza en casa." },
};

const PRODUCTOS = [
  {
    id: "spinning-3en1",
    categoria: "cardio",
    nombre: "Bicicleta spinning 3 en 1",
    gancho: "Tres rutinas en una sola bici",
    uso: "La armas en la sala y pedaleas viendo tu serie favorita.",
    datos: ["Volante de 6 kg, soporta hasta 100 kg", "Escáner digital, asiento y timón regulables", "Incluye disco twist y ligas; regalo: mat de yoga, hand grip y bandas"],
    precio: 350,
    imagenes: ["assets/productos/cardio/bicicleta-spinning-3en1-regalos.jpg"],
    mensaje: "Hola, tengo una consulta sobre la bicicleta spinning 3 en 1.",
  },
  {
    id: "spinning-12kg",
    categoria: "cardio",
    nombre: "Bicicleta spinning volante 12 kg",
    gancho: "Más peso, pedaleo más firme",
    uso: "Ideal si buscas más resistencia al pedalear sin salir de casa.",
    datos: ["Volante de 12 kg", "Asiento y timón regulables", "Regalo: rueda abdominal de un rebote"],
    precio: 530,
    imagenes: ["assets/productos/cardio/bicicleta-spinning-volante-12kg.jpg"],
    mensaje: "Hola, quiero consultar por la bicicleta spinning de volante 12 kg.",
  },
  {
    id: "spinning-15kg",
    categoria: "cardio",
    nombre: "Bicicleta spinning volante 15 kg",
    gancho: "El volante más pesado, más exigente",
    uso: "Perfecta si ya entrenas seguido y quieres más estabilidad al pedalear.",
    datos: ["Soporta hasta 150 kg", "Escáner digital: tiempo, distancia, calorías, velocidad y pulso", "Asiento y timón regulables"],
    precio: 745,
    precioAntes: 1240,
    imagenes: ["assets/productos/cardio/bicicleta-spinning-volante-15kg.jpg"],
    mensaje: "Hola, quiero consultar la bicicleta spinning de volante 15 kg.",
  },
  {
    id: "eliptica",
    categoria: "cardio",
    nombre: "Bicicleta elíptica multifuncional",
    gancho: "Cardio suave para las articulaciones",
    uso: "Combinas caminata, giro de cintura y pesas en una sola sesión en casa.",
    datos: ["Incluye disco twist y pesas", "Sistema LED", "Trabaja brazos y piernas a la vez"],
    precio: 680,
    imagenes: ["assets/productos/cardio/bicicleta-eliptica-multifuncional.jpg"],
    mensaje: "Hola, quiero información de la bicicleta elíptica multifuncional.",
  },
  {
    id: "trotadora-electrica",
    categoria: "cardio",
    nombre: "Trotadora eléctrica con masajeador",
    gancho: "Corre en casa y relaja después",
    uso: "Trotas a tu ritmo y usas el masajeador para aflojar las piernas al final.",
    datos: ["Motor 2.0 HP, de 1 a 12 km/h", "3 niveles de inclinación manual", "Soporta hasta 100 kg"],
    precio: 1100,
    precioAntes: 1500,
    imagenes: ["assets/productos/cardio/trotadora-electrica-masajeador.jpg"],
    mensaje: "Hola, quiero consultar la trotadora eléctrica con masajeador.",
  },
  {
    id: "trotadora-mecanica",
    categoria: "cardio",
    nombre: "Trotadora mecánica 5 en 1",
    gancho: "Cinco máquinas en un solo equipo",
    uso: "Alternas caminata, trote, escaladora y abdomen sin cambiar de máquina.",
    datos: ["Camina, corre, escaladora, disco twist y barras push-up", "Soporta hasta 100 kg", "Sistema de amortiguación"],
    precio: 650,
    imagenes: ["assets/productos/cardio/trotadora-mecanica-5en1.jpg"],
    mensaje: "Hola, quiero saber más de la trotadora mecánica 5 en 1.",
  },
  {
    id: "mancuernas-24",
    categoria: "fuerza",
    nombre: "Mancuernas regulables 24 kg",
    gancho: "Varias pesas en una sola mancuerna",
    uso: "Ajustas el peso en segundos y guardas todo el set en poco espacio.",
    datos: ["Hasta 24 kg por mancuerna", "Ajuste rápido, diseño compacto", "S/400 la unidad o S/750 el par"],
    precio: 400,
    precioPar: 750,
    imagenes: ["assets/productos/fuerza/mancuernas-regulables-24kg.jpg"],
    mensaje: "Hola, quiero consultar las mancuernas regulables de 24 kg.",
  },
  {
    id: "mancuernas-40",
    categoria: "fuerza",
    nombre: "Mancuernas regulables 40 kg",
    gancho: "Más peso para seguir progresando",
    uso: "Subes de peso sin comprar mancuernas nuevas cada vez que avanzas.",
    datos: ["Hasta 40 kg por mancuerna", "Ajuste rápido, diseño compacto", "S/600 la unidad o S/1100 el par"],
    precio: 600,
    precioPar: 1100,
    imagenes: ["assets/productos/fuerza/mancuernas-regulables-40kg.jpg"],
    mensaje: "Hola, quiero información de las mancuernas regulables de 40 kg.",
  },
  {
    id: "banca-plana",
    categoria: "fuerza",
    nombre: "Banca plana DDS",
    gancho: "La base de tu rutina de fuerza",
    uso: "La usas para pecho, hombro o abdomen, y la guardas donde sea.",
    datos: ["Soporta hasta 200 kg", "Patas de acero, pesa 14.5 kg", "Mide 110 × 65 × 41 cm"],
    precio: 300,
    precioAntes: 490,
    imagenes: ["assets/productos/fuerza/banca-plana-dds.jpg"],
    mensaje: "Hola, quiero consultar la banca plana DDS.",
  },
  {
    id: "banca-pecho",
    categoria: "fuerza",
    nombre: "Banca de pecho DDS + predicador",
    gancho: "Una banca, varios ejercicios",
    uso: "Cambias de posición para trabajar pecho, hombros, glúteos o brazos en la misma banca.",
    datos: ["Multiposición", "Incluye predicador para brazos", "Pecho, hombros, glúteos y brazos"],
    precio: 450,
    imagenes: [
      "assets/productos/fuerza/banca-pecho-dds-predicador.jpg",
      "assets/productos/fuerza/banca-pecho-dds-ejercicios.jpg",
      "assets/productos/fuerza/banca-pecho-dds-producto.jpg",
    ],
    mensaje: "Hola, quiero información de la banca de pecho DDS con predicador.",
  },
  {
    id: "barra-pared",
    categoria: "fuerza",
    nombre: "Barra de ejercicios 6 en 1 de pared",
    gancho: "Dominadas sin salir de casa",
    uso: "La instalas en la pared y haces dominadas, fondos y abdomen cuando quieras.",
    datos: ["Dominadas, fondos, tríceps y elevación de rodillas", "Se instala en la pared", "Regalo: push-up, ligas, hand grip y barra de torsión"],
    precio: 250,
    imagenes: ["assets/productos/fuerza/barra-ejercicios-6en1-pared.jpg"],
    mensaje: "Hola, quiero consultar la barra de ejercicios 6 en 1 de pared.",
  },
  {
    id: "barra-recta",
    categoria: "fuerza",
    nombre: "Barra recta 1.80 m",
    gancho: "El clásico de toda rutina de fuerza",
    uso: "La usas para press, sentadilla o peso muerto en tu propio espacio.",
    datos: ["Mide 1.80 m", "Incluye seguros para discos", "Precio a consultar"],
    precio: null,
    imagenes: ["assets/productos/fuerza/barra-recta-1-80m.jpg"],
    mensaje: "Hola, quiero consultar el precio de la barra recta de 1.80 m.",
  },
  {
    id: "banca-abdominal-ligas",
    categoria: "core",
    nombre: "Banca abdominal con ligas",
    gancho: "Abdomen y brazos en una banca",
    uso: "La usas para abdominales y sumas las ligas para trabajar brazos y espalda.",
    datos: ["Incluye ligas de resistencia", "Incluye 2 mancuernas de 1 kg", "Ideal para casa o gimnasio"],
    precio: 190,
    precioAntes: 310,
    imagenes: ["assets/productos/core/banca-abdominal-con-ligas.jpg"],
    mensaje: "Hola, quiero consultar la banca abdominal con ligas.",
  },
  {
    id: "banca-abdominal-pro",
    categoria: "core",
    nombre: "Banca abdominal Fitness Pro",
    gancho: "Abdomen, piernas y glúteos en uno",
    uso: "La usas para elevar piernas, hacer push-up o trabajar abdomen y glúteos.",
    datos: ["Elevación de piernas", "Push-up", "Abdominales y glúteos"],
    precio: 400,
    imagenes: ["assets/productos/core/banca-abdominal-fitness-pro.jpg"],
    mensaje: "Hola, quiero información de la banca abdominal Fitness Pro.",
  },
  {
    id: "ab-shaper",
    categoria: "core",
    nombre: "AB Shaper",
    gancho: "Abdomen, brazos y glúteos, compacto",
    uso: "Lo usas unos minutos al día para trabajar abdomen, brazos y glúteos.",
    datos: ["Trabaja abdomen, brazos y glúteos", "Escáner digital", "Estructura resistente"],
    precio: 180,
    precioAntes: 300,
    imagenes: ["assets/productos/core/ab-shaper.jpg"],
    mensaje: "Hola, quiero consultar el AB Shaper.",
  },
  {
    id: "ab-coaster",
    categoria: "core",
    nombre: "AB Coaster",
    gancho: "Movimiento guiado para tu abdomen",
    uso: "Deslizas el asiento en curva para trabajar el core y el recto abdominal.",
    datos: ["Trabaja core y recto abdominal", "Incluye ligas y disco twist", "Diseño compacto"],
    precio: 290,
    precioAntes: 530,
    imagenes: ["assets/productos/core/ab-coaster.jpg"],
    mensaje: "Hola, quiero información del AB Coaster.",
  },
  {
    id: "set-rosa",
    categoria: "linea-rosa",
    nombre: "Set de pesas 2 en 1",
    gancho: "Mancuerna y pesa rusa en uno",
    uso: "Lo armas como mancuerna o como pesa rusa según lo que quieras trabajar.",
    datos: ["Hasta 5 kg en total", "Peso modificable por bloques", "Compacto y fácil de guardar"],
    precio: 180,
    imagenes: [
      "assets/productos/linea-rosa/set-pesas-2en1-rosa.jpg",
      "assets/productos/linea-rosa/mancuernas-ajustables-rosa.jpg",
      "assets/productos/linea-rosa/contrapeso-ajustable-rosa.jpg",
      "assets/productos/linea-rosa/kettlebell-ajustable-rosa.jpg",
      "assets/productos/linea-rosa/set-2en1-desmontable-rosa.jpg",
      "assets/productos/linea-rosa/kettlebell-ejercicios-rosa.jpg",
    ],
    mensaje: "Hola, quiero consultar el set de pesas 2 en 1 de la línea rosa.",
  },
];

/* Kits sugeridos: combinaciones reales del catálogo (el total se calcula solo) */
const KITS = [
  { nombre: "Rincón de fuerza", espacio: "Un rincón de la sala (la banca mide 110 × 65 cm)", productos: ["banca-plana", "mancuernas-24"], nota: "Mancuernas en par", par: true },
  { nombre: "Cardio para empezar", espacio: "Una esquina de la sala", productos: ["spinning-3en1", "ab-shaper"] },
  { nombre: "Core en 15 minutos", espacio: "Espacio de un mat de yoga, más la banca", productos: ["banca-abdominal-ligas", "ab-coaster"] },
  { nombre: "Poco espacio, rutina completa", espacio: "Una pared libre", productos: ["barra-pared", "set-rosa"] },
  { nombre: "Cuarto de entrenamiento", espacio: "Un cuarto dedicado", productos: ["trotadora-electrica", "banca-pecho", "mancuernas-24"] },
];

/* Rutinas de 20 minutos (orientativas, nivel principiante) */
const RUTINAS = [
  { nombre: "Arranque spinning 20", equipo: ["spinning-3en1", "spinning-12kg", "spinning-15kg"], pasos: ["Calentamiento suave, 3 min", "5 × (1 min ritmo firme + 1 min suave)", "3 × 1 min a ritmo moderado", "Pedaleo suave de enfriamiento, 3 min", "Estiramiento de piernas, 1 min"] },
  { nombre: "Elíptica sin impacto", equipo: ["eliptica"], pasos: ["Calentamiento a ritmo bajo, 3 min", "4 × (2 min ritmo medio + 1 min suave)", "Ritmo bajo, 3 min", "Estiramiento de pantorrillas y espalda, 2 min"] },
  { nombre: "Caminata activa en casa", equipo: ["trotadora-mecanica", "trotadora-electrica"], pasos: ["Caminata suave, 4 min", "3 × (2 min paso firme + 1 min caminata)", "Caminata de recuperación, 4 min", "Movilidad de tobillos y cadera, 3 min"] },
  { nombre: "Tren superior express", equipo: ["mancuernas-24", "banca-plana"], pasos: ["Press de banca con mancuernas: 3 × 10-12", "Remo con mancuerna apoyado en banca: 3 × 10-12", "Elevaciones laterales: 2 × 12", "Curl de bíceps: 2 × 12", "Estiramiento de brazos y hombros, 2 min"] },
  { nombre: "Pecho y brazos en casa", equipo: ["banca-pecho", "barra-recta"], pasos: ["Press de pecho en banca: 3 × 10", "Curl en predicador: 3 × 10", "Aperturas con mancuernas: 2 × 12", "Extensión de tríceps: 2 × 12"] },
  { nombre: "Core suave 20", equipo: ["banca-abdominal-ligas", "ab-shaper"], pasos: ["Movilidad de columna, 3 min", "Abdominales en banca con ligas: 3 × 12", "AB Shaper con balanceo controlado: 3 × 30 s", "Plancha: 3 × 20 s", "Estiramiento lumbar, 2 min"] },
];
